# modules/nixos/hosts/hp-probook/hardware-configuration.nix
{
  config,
  lib,
  modulesPath,
  ...
}: {
  # Import base hardware scanning module
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # ═══════════════════════════════════════════════════════════
  # KERNEL MODULES & HARDWARE
  # Generated by nixos-generate-config --show-hardware-config
  # ═══════════════════════════════════════════════════════════
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "sr_mod"
    "sdhci_pci"
  ];

  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
